# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c16aa49423ec5c16d099d8be0228c50cb705972ed1b79b66de70aa71fd1f67c2aad40474412f1671a2c37105da77d84f73240086394b52252ac3a1754146497d

test:
  secret_key_base: 498338dfea788be6ae06a8199059eb5d8f025dd37d4896c35f503d8b5670855e6bf6adb741ca9ce51cd3b92b592a3ce51aeb322ebc25f4e817eb57816c735547

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
